### PR TITLE
DesKeyChecker.check() => check the change multipath is not hardened

### LINKED ISSUE #1183: [Installer] improve descriptor/xpub validation
- we can import a descriptor w/ a hardened multipath (`<0;1'>`) ending up the daemon panic and installer stuck (cannot go back previous step):

image

```rust
  2024-07-10T03:40:22.543082Z ERROR liana:60: panic occurred at line 611 of file /vendor/liana/src/descriptors/mod.rs: Some("May only fail on hardened derivation indexes, but we ruled out this case.: TranslatorErr(HardenedChild)")
   0: liana::setup_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: <unknown>
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: liana::database::sqlite::utils::create_fresh_db
   8: liana::database::sqlite::SqliteDb::new
   9: liana::setup_sqlite
  10: liana::DaemonHandle::start_default
  11: liana_gui::installer::daemon_check
  12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  13: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  15: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  16: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  17: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: tokio::runtime::task::raw::poll
  21: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  22: tokio::runtime::scheduler::multi_thread::worker::Context::run
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
  24: tokio::runtime::scheduler::multi_thread::worker::run
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  26: tokio::runtime::task::core::Core<T,S>::poll
  27: tokio::runtime::task::harness::Harness<T,S>::poll
  28: tokio::runtime::blocking::pool::Inner::run
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: <unknown>
  32: <unknown>
  33: <unknown>

```

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR add a check to verify that the change descriptor is not hardened.
without this check it allow import of invalid (not  derivable change) multipath like <0;1'> into a LianaDescriptor.

closes #1183

### CODE REVIEW

File: src/descriptors/analysis.rs [hunk 1]
```diff
@@ -31,6 +31,7 @@ pub enum LianaPolicyError {
     /// The spending policy is not a valid Miniscript policy: it may for instance be malleable, or
     /// overflow some limit.
     InvalidPolicy(miniscript::Error),
+    HardenedMultipath,
```
Comment (jp1ac4) [inline src/descriptors/analysis.rs:34]: Would it be better to call it `HardenedDerivationStep` (comparing with the comments in the function)?

File: src/descriptors/analysis.rs [hunk 2]
```diff
@@ -61,6 +62,7 @@ impl std::fmt::Display for LianaPolicyError {
             ),
             Self::InvalidPolicy(e) => write!(f, "Invalid Miniscript policy: {}", e),
             Self::PolicyAnalysis(e) => write!(f, "Analyzing the policy of the miniscript: {}", e),
+            LianaPolicyError::HardenedMultipath => write!(f, "Hardened multipaths are forbiden"),
```
Comment (jp1ac4) [inline src/descriptors/analysis.rs:65]: You could use `Self::` here for consistency with other lines.

Typo: "forbidden".

File: src/descriptors/analysis.rs [hunk 3]
```diff
@@ -117,10 +119,12 @@ impl DescKeyChecker {
             if let Some(ref origin) = xpub.origin {
                 let der_paths = xpub.derivation_paths.paths();
                 let first_der_path = der_paths.first().expect("Cannot be empty");
+                let second_der_path = &der_paths[1];
                 // We also rule out xpubs with hardened derivation steps (non-normalized xpubs).
                 let valid = xpub.wildcard == descriptor::Wildcard::Unhardened
                     && der_paths.len() == 2
-                    && first_der_path.into_iter().all(|step| step.is_normal());
+                    && first_der_path.into_iter().all(|step| step.is_normal())
+                    && second_der_path.into_iter().all(|step| step.is_normal());
```
Comment (jp1ac4) [inline src/descriptors/analysis.rs:127]: Perhaps here you could combine both checks into a single line using `der_paths.into_iter().flatten()`.

**Review by jp1ac4 — COMMENTED** [review]
I've added a few comments.

Also, would it be possible to add a test for `check()` that produces this error?

File: src/descriptors/analysis.rs [hunk 4]
```diff
@@ -117,10 +119,12 @@ impl DescKeyChecker {
             if let Some(ref origin) = xpub.origin {
                 let der_paths = xpub.derivation_paths.paths();
                 let first_der_path = der_paths.first().expect("Cannot be empty");
+                let second_der_path = &der_paths[1];
```
Comment (darosior) [inline src/descriptors/analysis.rs:122]: Why would this vector always have at least two elements?

**Review by darosior — COMMENTED** [review]
Concept ACK. I think we should consider this a bug fix and have it for v7.

File: src/descriptors/analysis.rs (hunk 4 above)
Comment (pythcoiner) [reply src/descriptors/analysis.rs]: I guessed as `xpub` is a `MultiXPub` it should have at least 2 paths, but yeah it seems we can create a single element `DerivPaths`.

**Comment by pythcoiner** [comment]
I've dropped `LianaPolicyError::HardenedMultipath` error variant as it was not used anymore in my changes & i think `LianaPolicyError::InvalidKey` message is explicit enough and addressed @jp1ac4 comment about `der_paths`.
Also added some test cases.

File: src/descriptors/analysis.rs [hunk 5]
```diff
@@ -776,3 +775,72 @@ impl PartialSpendInfo {
...
+            checker.check(&key),
+            Err(LianaPolicyError::InvalidKey(_))
+        ));
+
+        // No multipath
+        let xpub_str =
+            "[8c3ffb6e/48'/1'/0'/2']tpubDEMt3bpQMa99W81K9h8f2FJH1C81eSd6bbSkBP8tcqQHAfSKvuGp2fz6xiVpfShzT9sKPx7DVBphChjxvNd15WcbsCca5oVz1AcUTWHxkdS/0/*";
+        let key = descriptor::DescriptorPublicKey::from_str(xpub_str).unwrap();
+        let mut checker = DescKeyChecker::new();
+        println!("{:?}", checker.check(&key));
```
Comment (jp1ac4) [inline src/descriptors/analysis.rs:810]: nit: can this line be removed?

File: src/descriptors/analysis.rs [hunk 6]
```diff
@@ -776,3 +775,72 @@ impl PartialSpendInfo {
...
+    #[test]
+    fn invalid_key() {
+        // Multipath of size 3
+        let xpub_str =
+            "[8c3ffb6e/48'/1'/0'/2']tpubDEMt3bpQMa99W81K9h8f2FJH1C81eSd6bbSkBP8tcqQHAfSKvuGp2fz6xiVpfShzT9sKPx7DVBphChjxvNd15WcbsCca5oVz1AcUTWHxkdS/<0;1;2>/*";
+        let key = descriptor::DescriptorPublicKey::from_str(xpub_str).unwrap();
+        let mut checker = DescKeyChecker::new();
+        assert!(matches!(
+            checker.check(&key),
+            Err(LianaPolicyError::InvalidKey(_))
```
Comment (jp1ac4) [inline src/descriptors/analysis.rs:802]: nit: I don't think you need to change it, but I was just thinking that to be sure the error contains `key`, perhaps this could be changed to:
```
assert!(matches!(
    checker.check(&key),
    Err(LianaPolicyError::InvalidKey(k)) if k == key.into()
));
```
I'm not sure if this is best practice, but it just occurred to me while reviewing.

**Review by jp1ac4 — COMMENTED** [review]
Thanks for the updates. I just have a couple of nits, one of which I think can be ignored.

**Comment by pythcoiner** [comment]
addressed both comments

**Review by jp1ac4 — APPROVED** [review]
ACK 8d495579e1f0b2bd329d3d299e707491c02a31bd.

**Review by darosior — APPROVED** [review]
Neat.

ACK 8d495579e1f0b2bd329d3d299e707491c02a31bd
