### PR TITLE
Fix error message when importing desc for wrong network

### LINKED ISSUE #781: GUI: Installer: clearer error on descriptor import for wrong network
When importing a descriptor, making a mistake when choosing the network on the first screen results in a pretty scary "INCOMPATIBLE DESCRIPTOR" error on the second screen when we copy paste the descriptor.

It would be nicer to just let them know the network is wrong.

### PR DESCRIPTION
**Pull request by edouardparis**
close #781

### CODE REVIEW

File: gui/src/installer/view.rs [hunk 1]
```diff
@@ -392,7 +393,11 @@ pub fn import_descriptor<'a>(
             form::Form::new_trimmed("Descriptor", imported_descriptor, |msg| {
                 Message::DefineDescriptor(message::DefineDescriptor::ImportDescriptor(msg))
             })
-            .warning("Incompatible descriptor.")
+            .warning(if wrong_network {
+                "The descriptor is for an other network, you can change the network in the previous steps."
+            } else {
+                "Incompatible descriptor."
```
Comment (darosior) [inline gui/src/installer/view.rs:399]: Could we have a less coloured error message in the general case? Like "error reading descriptor". "Incompatible" can freak a user out as it can be read as "we successfully read your descriptor and it's not compatible with this software", and it's often not the case.

**Review by jp1ac4 — COMMENTED** [review]
I reviewed https://github.com/wizardsardine/liana/pull/933/commits/04e9d9d0c12ebe9e5b173689912d03a557097e1d and left a comment regarding the message wording.

**Review by edouardparis — COMMENTED** [review]
Self-ACK 24f67d2a85b12730c669c4c7e311a534f75cc0ad
