### PR TITLE
gui: allow to connect to an electrum server w/ a self signed certificate

### LINKED ISSUE #1300: electrum: fail to connect to a server w/ a self-signed certificate
we actually fails to connect (in ssl) to an electrum server that have a self-signed certificate, in order to allow it we should have a look to few points:

- add an option to installer/settings to allow user to disable the certificate check, we should keep the default behaviour to check the certificate.
- certificate check should be disabled if we set electrum_client::Config `validate_domain` to `false` but not works as intended if electrum_client is used w/ default `use-rusttls` feauture. It works fine w/ `use-openssl` feature btw.
( i've opened an [issue](https://github.com/bitcoindevkit/bdk/issues/1598) about this disrepancy in bdk repo)
- `bdk_electrum` crate does not offer `use-openssl` feature:
```
    Updating crates.io index
      Adding bdk_electrum v0.17.0 to dependencies
             Features:
             + use-rustls
             - use-rustls-ring
```
bdk_electrum `Cargo.toml`:
```
[dependencies]
bdk_core = { path = "../core", version = "0.1" }
electrum-client = { version = "0.21", features = [ "proxy" ], default-features = false }

[dev-dependencies]
bdk_testenv = { path = "../testenv", default-features = false }
bdk_chain = { path = "../chain", version = "0.18.0" }

[features]
default = ["use-rustls"]
use-rustls = ["electrum-client/use-rustls"]
use-rustls-ring = ["electrum-client/use-rustls-ring"]
```

### PR DESCRIPTION
**Pull request by pythcoiner**
closes #1300 
The issue about connecting to an electrum certificate using `rustls` have been fixed [upstream](https://github.com/bitcoindevkit/bdk/issues/1598) but in order to beneficiate from it we have to update `bdk_electrum` and `rust-bitvoin` dependencies.
Meanwhile, this PR introduce a workaround: the initial issue is related to `electrum-client` `use-rustls` feature and `use-openssl` feature is not reexported by `bdk_electrum` but we can use `electrum-client` crate directly and use `use-openssl` feature by this way:
 - [x] use `electrum-client` directly w/ `use-openssl`
 - [x] add and option to opt-out of ssl domain validation
 - [x] let user change the `validate_domain` values in `Settings` menu.
 
image

 
 Note: ssl://testnet.aranguren.org:51002 electrum server can be used to test this PR

### CODE REVIEW

**Comment by jp1ac4** [comment]
In the GUI, could we add a "Use SSL" checkbox (related #1291), which, if selected, would then show the "validate domain" checkbox? If SSL is not required, then I feel it would be better not to show the validate option if it's not applicable.

Related to this, I wonder if we should use an enum in `ElectrumConfig` to include `validate_domain` only for the SSL case, e.g. something like `Tcp(url)` or `Ssl(url, validate_doman)`. I'm not sure `validate_domain` should be a manadatory field in the config file. Even in the SSL case, it could default to `false` if not present.

**Comment by nondiremanuel** [comment]
As we were discussing, let's have for now the validation checkbox (which I would phrase as "Do not validate SSL Domain (check this only if you want to use a self-signed certificate)") only if the user uses ssl in the address.

**Comment by pythcoiner** [comment]
the checkbox is now only displayed if the address is valid and contains "ssl://"

**Comment by pythcoiner** [comment]
> Related to this, I wonder if we should use an enum in `ElectrumConfig` to include `validate_domain` only for the SSL case, e.g. something like `Tcp(url)` or `Ssl(url, validate_domain)`. I'm not sure `validate_domain` should be a mandatory field in the config file. Even in the SSL case, it could default to `false` if not present.

i think this can be done in a follow-up if we decide to add a checkbox for enable/disable ssl instead prepending it to the address.

**Comment by jp1ac4** [comment]
> i think this can be done in a follow-up if we decide to add a checkbox for enable/disable ssl instead prepending it to the address.

OK yep, let's save that for a follow-up. We could probably keep the value saved in the config file as "ssl://..." and just change how it's parsed into `ElectrumConfig`.

For this present PR, I think you'll need to make `validate_domain` an `Option` so that it works with existing config files. In the case of SSL, it can then default to false if not present.

**Comment by pythcoiner** [comment]
> > i think this can be done in a follow-up if we decide to add a checkbox for enable/disable ssl instead prepending it to the address.
> 
> OK yep, let's save that for a follow-up. We could probably keep the value saved in the config file as "ssl://..." and just change how it's parsed into `ElectrumConfig`.
> 
> For this present PR, I think you'll need to make `validate_domain` an `Option` so that it works with existing config files. In the case of SSL, it can then default to false if not present.

i think having a default as true can avoid footgun and make sense, as it's the default value of the bdk electrum client, see [here](https://github.com/bitcoindevkit/rust-electrum-client/blob/15f753f05f588b2e871e1dc4e3ca7201b09b27d7/src/config.rs#L146)

**Comment by jp1ac4** [comment]
> i think having a default as true can avoid footgun and make sense, as it's the default value of the bdk electrum client, see [here](https://github.com/bitcoindevkit/rust-electrum-client/blob/15f753f05f588b2e871e1dc4e3ca7201b09b27d7/src/config.rs#L146)

Ah I see, and so this is also the value we've implicitly been using for SSL connections so far. I agree we can default to true then (also for the GUI checkbox).

**Comment by pythcoiner** [comment]
> > i think having a default as true can avoid footgun and make sense, as it's the default value of the bdk electrum client, see [here](https://github.com/bitcoindevkit/rust-electrum-client/blob/15f753f05f588b2e871e1dc4e3ca7201b09b27d7/src/config.rs#L146)
> 
> Ah I see, and so this is also the value we've implicitly been using for SSL connections so far. I agree we can default to true then (also for the GUI checkbox).

the checkbox follow the default, but checked mean "do NOT validate", so it's unchecked as default

**Comment by jp1ac4** [comment]
> the checkbox follow the default, but checked mean "do NOT validate", so it's unchecked as default

That sounds good then. I think it just remains to make `validate_domain` an `Option` in the config or otherwise to change how it's deserialized so that a missing value is treated as true.

**Comment by pythcoiner** [comment]
> That sounds good then. I think it just remains to make `validate_domain` an `Option` in the config or otherwise to change how it's deserialized so that a missing value is treated as true.

i've implemented default deserialization

File: liana-gui/src/installer/message.rs [hunk 1]
```diff
@@ -81,6 +81,7 @@ pub enum DefineBitcoind {
 #[derive(Debug, Clone)]
 pub enum DefineElectrum {
     ConfigFieldEdited(electrum::ConfigField, String),
+    ValidDomainChanged(bool),
```
Comment (jp1ac4) [inline liana-gui/src/installer/message.rs:84]: As `validate_domain` is part of the config, I feel that this should somehow also be part of `ConfigFieldEdited`. Perhaps you can use something like `ConfigFieldEdited(electrum::ConfigFieldValue)` where `ConfigFieldValue` is:
```
pub enum ConfigFieldValue {
    Address(String),
    ValidateDomain(bool),
}
```

File: liana-gui/src/app/view/settings.rs [hunk 2]
```diff
@@ -583,6 +584,16 @@ pub fn electrum_edit<'a>(
             .push(separation().width(Length::Fill));
     }
 
+    let checkbox = checkbox(
+        "Do not validate SSL Domain(check this only if you want to use a self-signed certificate)",
+        !validate_domain,
+    )
+    .on_toggle(|b| SettingsEditMessage::ValidateDomainEdited(!b));
+    let checkbox = if addr.valid && addr.value.contains("ssl://") {
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings.rs:592]: nit: The function `is_electrum_address_valid(value: &str)` uses `value.starts_with("ssl://")` so you could use the same condition here (or even add it to a standalone `is_ssl()` function and then use it within `is_electrum_address_valid`).

Also, to avoid repeating this checkbox logic in the installer, you could add it to src/node/electrum.rs.

File: liana-gui/src/app/view/message.rs [hunk 3]
```diff
@@ -88,6 +88,7 @@ pub enum RemoteBackendSettingsMessage {
 pub enum SettingsEditMessage {
     Select,
     FieldEdited(&'static str, String),
+    ValidateDomainEdited(bool),
```
[the remark this answers is not in the document]
Comment (pythcoiner) [reply liana-gui/src/app/view/message.rs:91]: i think we should not do this until we need it? looks like adding uneeded complexity imho

File: lianad/src/config.rs [hunk 4]
```diff
@@ -128,6 +128,19 @@ pub struct ElectrumConfig {
     /// Include "ssl://" for SSL. otherwise TCP will be assumed.
     /// Can optionally prefix with "tcp://".
     pub addr: String,
+    /// If validate_domain == false, domain of ssl certificate will not be validated
+    /// (useful to allow usage of self signed certificates on local network)
+    #[serde(default)]
```
[the remark this answers is not in the document]
Comment (pythcoiner) [reply lianad/src/config.rs:133]: any advantage doing this? i feel it's more natural/standard to use the standard `Default` mechanism instead a custom one? having default values for the whole struct should not be a problem imho?

File: liana-gui/src/installer/message.rs (hunk 1 above)
Comment (pythcoiner) [reply liana-gui/src/installer/message.rs:84]: `ValidDomainChanged(true)` is shorter than
`ConfigFieldEdited(electrum::ConfigFieldValue(electrum::ConfigFieldValue::ValidateDomain(bool)))`
the event system of iced is already overwhelming imho, we should avoid "overwrapping" it only make the codebase less readable & more error prone

Comment (jp1ac4) [reply liana-gui/src/installer/message.rs:84]: Wouldn't it be just `ConfigFieldEdited(electrum::ConfigFieldValue::ValidateDomain(bool))`?

And by removing `electrum::` it would be just `ConfigFieldEdited(ConfigFieldValue::ValidateDomain(bool))`.

It doesn't seem too bad, but we can leave it for now. If we have a separate message per field, then we should at some point change `ConfigFieldEdited` to `AddressEdited`.

File: liana-gui/src/app/view/message.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jp1ac4) [reply liana-gui/src/app/view/message.rs:91]: I suppose so, we may do further refactoring at some point when we allow switching between bitcoind and Electrum nodes in the settings.

File: lianad/src/config.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (jp1ac4) [reply lianad/src/config.rs:133]: It wasn't clear to me that the default address value is useful or makes sense here, and I felt we should only add the necessary default values. But it's probably fine either way.

**Comment by jp1ac4** [comment]
It would be good to add some comments to https://github.com/wizardsardine/liana/blob/master/contrib/lianad_config_example.toml about the new field.

File: liana-gui/src/installer/message.rs (hunk 1 above)
Comment (pythcoiner) [reply liana-gui/src/installer/message.rs:84]: at this point of the release cycle i'd like to bring this PR quickly to a mergeable state or put it on hold: to avoid everyone testing under the christmas tree :smile:

**Comment by pythcoiner** [comment]
> It would be good to add some comments to https://github.com/wizardsardine/liana/blob/master/contrib/lianad_config_example.toml about the new field.

adressed, feel free if you have better wording

File: liana-gui/src/installer/message.rs (hunk 1 above)
Comment (jp1ac4) [reply liana-gui/src/installer/message.rs:84]: That's OK, I meant it as something to consider in the future.

File: contrib/lianad_config_example.toml [hunk 5]
```diff
@@ -50,8 +50,13 @@ poll_interval_secs = 30
 # In order to connect, it needs the address as a string, which can be
 # optionally prefixed with "ssl://" or "tcp://". If omitted, "tcp://"
 # will be assumed.
+# `validate_domain` field is optionnal: used in case of SSL connection,
```
Comment (jp1ac4) [inline contrib/lianad_config_example.toml:53]: typo: "optional".

File: contrib/lianad_config_example.toml [hunk 6]
```diff
@@ -50,8 +50,13 @@ poll_interval_secs = 30
...
+# if set to `false`, internal electrum client will not try to validate
+# the domain associated to the certificate: it's usefull in case of
```
Comment (jp1ac4) [inline contrib/lianad_config_example.toml:55]: typo: "useful"

File: contrib/lianad_config_example.toml (hunk 5 above)
Comment (jp1ac4) [inline contrib/lianad_config_example.toml:53]: You could add that it defaults to true.

**Review by jp1ac4 — COMMENTED** [review]
Needs a rebase on master.

**Comment by pythcoiner** [comment]
> Needs a rebase on master.

rebsed & addressed comments

**Comment by jp1ac4** [comment]
In the case that SSL is being used, should we show in the read-only settings view a line to indicate whether `validate_domain` is true or false?

image

**Comment by pythcoiner** [comment]
> In the case that SSL is being used, should we show in the read-only settings view a line to indicate whether `validate_domain` is true or false?
> 
> image

no strong opinion, ping @nondiremanuel

**Comment by pythcoiner** [comment]
looks like CI failing on windows because missing openssl dependency...

File: lianad/src/config.rs (hunk 4 above)
Comment (jp1ac4) [inline lianad/src/config.rs:133]: This default doesn't seem to be working for me. If my config doesn't contain validate_domain, the value is set to false.

Comment (jp1ac4) [reply lianad/src/config.rs:133]: It's probably worth adding some unit tests for the `ElectrumConfig` parsing to complement the other config parsing tests.

Comment (pythcoiner) [reply lianad/src/config.rs]: fixed & added tests, the issue was serde use default of field type (false) and not default of the struct, my bad

**Comment by pythcoiner** [comment]
[5e5e65e](https://github.com/wizardsardine/liana/pull/1500/commits/5e5e65e849e1a5d2c6bd03ac002ba2bfaf6e667c) seems to fix windows CI

**Comment by nondiremanuel** [comment]
> > In the case that SSL is being used, should we show in the read-only settings view a line to indicate whether `validate_domain` is true or false?
> > image
> 
> no strong opinion, ping @nondiremanuel

It's not required at this stage imho.

File: contrib/lianad_config_example.toml [hunk 7]
```diff
@@ -50,8 +50,13 @@ poll_interval_secs = 30
 # In order to connect, it needs the address as a string, which can be
 # optionally prefixed with "ssl://" or "tcp://". If omitted, "tcp://"
 # will be assumed.
+# `validate_domain` field is optional: used in case of SSL connection,
+# if set to `false`, internal electrum client will not try to validate
+# the domain associated to the certificate: it's useful in case of 
+# self-signed certificate. It's default value is `true`.
```
Comment (jp1ac4) [inline contrib/lianad_config_example.toml:56]: nit: "It's" -> "Its"

File: liana-gui/src/installer/view/mod.rs [hunk 8]
```diff
@@ -1150,7 +1159,8 @@ pub fn define_electrum<'a>(address: &form::Value<String>) -> Element<'a, Message
             .size(text::P1_SIZE)
             .padding(10),
         )
-        .push(text(electrum::ADDRESS_NOTES).size(text::P2_SIZE))
```
Comment (jp1ac4) [inline liana-gui/src/installer/view/mod.rs:1153]: nit: Did you intend to remove the `.size(text::P2_SIZE)`?

File: lianad/Cargo.toml [hunk 9]
```diff
@@ -28,6 +28,7 @@ miniscript = { version = "11.0", features = ["serde", "compiler", "base64"] }
 # For Electrum backend. This is the latest version with the same bitcoin version as
 # the miniscript dependency.
 bdk_electrum = { version = "0.14" }
+electrum-client = {version = "0.19", features =["use-openssl"]}
```
Comment (jp1ac4) [inline lianad/Cargo.toml:31]: nit(formatting): `features = ["use-openssl"] }`

**Review by jp1ac4 — APPROVED** [review]
Tested ACK https://github.com/wizardsardine/liana/commit/5e5e65e849e1a5d2c6bd03ac002ba2bfaf6e667c.

A couple of nits and a question, but we can come back to those if need be.

File: liana-gui/src/installer/view/mod.rs (hunk 8 above)
Comment (pythcoiner) [reply liana-gui/src/installer/view/mod.rs:1153]: > yes I think I removed intentionally the size to stay consistant in the context, IIRC i notice the size was different from some others warnings

**Comment by pythcoiner** [comment]
comments addressed
