### PR TITLE
UI fixes & improvements

### LINKED ISSUE #1866: nits: Wording/spelling mistakes (will add more as i review the wallet)
Image
"It" with capital I.
I also suppose the future tense is important here: "It will help you identify it later"

### LINKED ISSUE #1868: Encrypted descriptors - buttons and location
In Settings > Wallet
We should rename the "Back up Descriptor" button to "Back up encrypted descriptor" or "Export encrypted descriptor"
An infotip would be useful, if we find the place to put it:
"An encrypted descriptor file (.bed) you can store anywhere. To decrypt it, you need one of your signing devices or xpub."

In Settings > Import/Export
Add an option "Encrypted Descriptor" ".bed file, can be decrypted with one of your signing device or xpub."
Put this option at the top of the list, as it is now more important/recommended than the Export Wallet until we have encrypted wallet backups.

In the description of Export Wallet, add that this is not encrypted.

Rename the "Descriptor only" option in other formats to "Descriptor only - plain-text". In the description, add "Plain-text (not encrypted)..."

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR:
 - Add a tooltip that displays derivation paths (useful for airgap devices users)
 - Fix scrollbar overlaping buttons in `DecryptModal`
 - Hint the user it's unsafe to enter a mnemonic in `DecryptModal`
 - Change somes wording in `Settings` > `Wallet` & `Settings` > `Import/Export`
 - Add option for export encrypted descriptor in `Settings` > `Import/Export`
 - Fix wording in key editing modal
 - Fix alignment in `DecryptModal`
 - closes #1868 
 - closes #1866

### CODE REVIEW

File: liana-gui/src/app/view/settings/mod.rs [hunk 1]
```diff
@@ -1009,6 +1017,16 @@ pub fn wallet_settings<'a>(
     updated: bool,
 ) -> Element<'a, Message> {
     let header = header("Wallet", SettingsMessage::EditWalletSettings);
+    let r = Row::new().spacing(10).align_y(Vertical::Center)
+        .push(icon::backup_icon())
+        .push(text("Back Up Encrypted Descriptor"))
+        .push(tooltip("An encrypted descriptor file (.bed) you can store anywhere. To decrypt it, you need one of your signing devices or xpub."));
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings/mod.rs]: Should it be "xpubs"?

File: liana-gui/src/installer/decrypt.rs [hunk 2]
```diff
@@ -592,10 +600,28 @@ fn valid_content(state: &DecryptModal) -> Container<'static, installer::Message>
...
+    for d in &state.derivation_paths {
+        tt = tt.push(text::text(format!("{d}")));
+    }
+    let tt = Container::new(tt)
+        .style(theme::card::simple)
+        .padding(10)
+        .width(300);
+
+    let airgap_hint = Row::new()
+        .push(p1_regular("Provide one of the xpub used in this wallet."))
```
Comment (jp1ac4) [inline liana-gui/src/installer/decrypt.rs]: "xpubs"

File: liana-gui/src/installer/decrypt.rs [hunk 3]
```diff
@@ -615,28 +641,87 @@ fn optional_content(state: &DecryptModal) -> Container<'static, installer::Messa
...
 
     Container::new(col)
 }
 
+#[allow(clippy::too_many_arguments)]
+pub fn mnemonic_input_button<'a>(
+    collapsed: bool,
+    ack: bool,
+    input_value: &Value<String>,
+    // ack_message: Message,
```
Comment (jp1ac4) [inline liana-gui/src/installer/decrypt.rs]: nit: can remove commented line?

File: liana-gui/src/app/view/settings/mod.rs (hunk 1 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

File: liana-gui/src/installer/decrypt.rs (hunk 2 above)
Comment (pythcoiner) [reply liana-gui/src/installer/decrypt.rs]: done

File: liana-gui/src/installer/decrypt.rs (hunk 3 above)
Comment (pythcoiner) [reply liana-gui/src/installer/decrypt.rs]: done

File: liana-gui/src/app/view/settings/mod.rs [hunk 4]
```diff
@@ -216,13 +216,20 @@ pub fn import_export<'a>(cache: &'a Cache, warning: Option<&Error>) -> Element<'
         ))
         .push(Space::with_width(Length::Fill));
 
-    let export_descriptor = export_section(
-        "Descriptor only",
-        "Plain-text descriptor file only, to use with other wallets.",
+    let export_encrypted_descriptor = export_section(
+        "Encrypted Descriptor",
+        ".bed file, can be decrypted with one of your signing device or xpub.",
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings/mod.rs]: I missed this one before: "...signing devices or xpubs".

File: liana-gui/src/app/view/settings/mod.rs [hunk 5]
```diff
@@ -216,13 +216,20 @@ pub fn import_export<'a>(cache: &'a Cache, warning: Option<&Error>) -> Element<'
         ))
         .push(Space::with_width(Length::Fill));
 
-    let export_descriptor = export_section(
-        "Descriptor only",
-        "Plain-text descriptor file only, to use with other wallets.",
+    let export_encrypted_descriptor = export_section(
+        "Encrypted Descriptor",
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings/mod.rs]: I think lowercase "descriptor" would be more consistent with the other options on this page.

File: liana-gui/src/installer/step/descriptor/editor/key.rs [hunk 6]
```diff
@@ -1393,7 +1393,7 @@ where
             Space::with_width(Length::Fill)
         ])
         .push(row![
-            p1_regular("Give this key a friendly name. it helps you identify it later:"),
+            p1_regular("Give this key a friendly name. It helps you identify it later:"),
```
Comment (jp1ac4) [inline liana-gui/src/installer/step/descriptor/editor/key.rs]: nit: I think "It will help you..." reads better.

File: liana-gui/src/app/view/settings/mod.rs [hunk 7]
```diff
@@ -1009,6 +1017,16 @@ pub fn wallet_settings<'a>(
     updated: bool,
 ) -> Element<'a, Message> {
     let header = header("Wallet", SettingsMessage::EditWalletSettings);
+    let r = Row::new().spacing(10).align_y(Vertical::Center)
+        .push(icon::backup_icon())
+        .push(text("Back Up Encrypted Descriptor"))
+        .push(tooltip("An encrypted descriptor file (.bed) you can store anywhere. To decrypt it, you need one of your signing devices or xpubs."));
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings/mod.rs]: nit: I think using `Position::Bottom` for the tooltip would look a bit tidier.

File: liana-gui/src/app/view/settings/mod.rs [hunk 8]
```diff
@@ -1009,6 +1017,16 @@ pub fn wallet_settings<'a>(
     updated: bool,
 ) -> Element<'a, Message> {
     let header = header("Wallet", SettingsMessage::EditWalletSettings);
+    let r = Row::new().spacing(10).align_y(Vertical::Center)
+        .push(icon::backup_icon())
+        .push(text("Back Up Encrypted Descriptor"))
```
Comment (jp1ac4) [inline liana-gui/src/app/view/settings/mod.rs]: nit: for consistency with the other buttons on this page, I would only capitalise the first word.

**Review by jp1ac4 — COMMENTED** [review]
Successfully tested 2905e766a553086166a19f9f660bded46b938f99, including the new checkbox when entering the mnemonic.

Just a few more comments to consider.

File: liana-gui/src/app/view/settings/mod.rs (hunk 8 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

File: liana-gui/src/app/view/settings/mod.rs (hunk 4 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

File: liana-gui/src/app/view/settings/mod.rs (hunk 5 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

File: liana-gui/src/installer/step/descriptor/editor/key.rs (hunk 6 above)
Comment (pythcoiner) [reply liana-gui/src/installer/step/descriptor/editor/key.rs]: done

File: liana-gui/src/app/view/settings/mod.rs (hunk 7 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

File: liana-gui/src/app/view/settings/mod.rs (hunk 8 above)
Comment (pythcoiner) [reply liana-gui/src/app/view/settings/mod.rs]: done

**Review by jp1ac4 — APPROVED** [review]
tACK 022d98d767a1a7a6e7d420935c8b0b6197dc40cf.
