### PR TITLE
Use create_spend to calculate amount left to select and coin selection

### LINKED ISSUE #822: GUI: setting a too high feerate for a Spend crashes the software
We should really avoid careless conversions. Or idk sanitize inputs. 

```
  2023-11-17T13:19:00.521450Z ERROR liana:55: panic occurred at line 278 of file src/app/state/spend/step.rs: Some("attempt to multiply with overflow")                                                            
   0: liana::setup_panic_hook::{{closure}}                                                                                                                                                                         
             at /home/darosior/.cargo/git/checkouts/liana-efb3a908181ef2cf/2d303b1/src/lib.rs:49:18                                                                                                                
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call                                                                                                                                              
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2021:9                                                                                                                  
      std::panicking::rust_panic_with_hook                                                                                                                                                                         
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:711:13                                                                                                                
   2: std::panicking::begin_panic_handler::{{closure}}                                                                                                                                                             
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:597:13                                                                                                                
   3: std::sys_common::backtrace::__rust_end_short_backtrace                                                                                                                                                       
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18                                                                                                     
   4: rust_begin_unwind                                                                                                                                                                                            
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5                                                                                                                 
   5: core::panicking::panic_fmt                                                                                                                                                                                   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14                                                                                                                
   6: core::panicking::panic                                                                                                                                                                                       
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5                                                                                                                
   7: liana_gui::app::state::spend::step::DefineSpend::amount_left_to_select                                                                                                                                       
             at src/app/state/spend/step.rs:278:34                                                                                                                                                                 
   8: <liana_gui::app::state::spend::step::DefineSpend as liana_gui::app::state::spend::step::Step>::update                                                                                                        
             at src/app/state/spend/step.rs:320:29                                                                                                                                                                 
   9: <liana_gui::app::state::spend::CreateSpendPanel as liana_gui::app::state::State>::update                                                                                                                     
             at src/app/state/spend/mod.rs:105:20                                                                                                                                                                  
  10: liana_gui::app::App::update                                                                                                                                                                                  
             at src/app/mod.rs:174:18                                                                                                                                                                              
  11: <liana_gui::GUI as iced::application::Application>::update                                                                                                                                                   
             at src/main.rs:248:17                                                                                                                                                                                 
  12: <iced::application::Instance<A> as iced_native::program::Program>::update                                                                                                                                    
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced-0.9.0/src/application.rs:227:9                                                                                            
  13: iced_winit::application::update::{{closure}}
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:664:40
  14: iced_futures::backend::native::tokio::<impl iced_futures::executor::Executor for tokio::runtime::runtime::Runtime>::enter                                                                                     
             at /home/darosior/.cargo/git/checkouts/iced-01eedf742052ef90/2d8318b/futures/src/backend/native/tokio.rs:19:9     
  15: iced_futures::runtime::Runtime<Hasher,Event,Executor,Sender,Message>::enter                         
             at /home/darosior/.cargo/git/checkouts/iced-01eedf742052ef90/2d8318b/futures/src/runtime.rs:53:9                                                                                                       
  16: iced_winit::application::update                                                                     
             at /home/darosior/.cargo/registry/src/index.crates.io-6f17d22bba15001f/iced_winit-0.9.1/src/application.rs:664:23                                                                                      
```

https://github.com/wizardsardine/liana/blob/514535d8d6fec705c7271241f68276c42b918150/gui/src/app/state/spend/step.rs#L173-L236

### PR DESCRIPTION
**Pull request by edouardparis**
Fixes #822. based on #865

### CODE REVIEW

**Comment by darosior** [comment]
Does this also fix #840?

**Comment by edouardparis** [comment]
20231211_15h18m02s_grim

So it does not crash anymore, but I think I should add a limit of 1000 to the form to just have an "invalid" form in red instead of having the big error banner.

**Comment by pythcoiner** [comment]
> So it does not crash anymore, but I think I should add a limit of 1000 to the form to just have an "invalid" form in red instead of having the big error banner.

do this will 'lock' the step so the user cannot continue further? or just a hint?
1000 is just 3 times the sats/vbytes we experience few weeks ago, what if the fee go over this amount in few weeks/month?

**Comment by darosior** [comment]
> do this will 'lock' the step so the user cannot continue further? or just a hint?

The user will encounter the same error if they click on "Next".

>  1000 is just 3 times the sats/vbytes we experience few weeks ago, what if the fee go over this amount in few weeks/month?

Yeah we might have to update our "max sane feerate", but that should be separate from this which just reuses what we use elsewhere.

File: gui/src/app/state/spend/step.rs [hunk 1]
```diff
@@ -175,110 +188,121 @@ impl DefineSpend {
...
+                            sequence: None,
+                            must_select: *selected,
+                        })
+                    } else {
+                        None
+                    }
+                })
+                .collect()
+        } else {
+            self.coins
```
Comment (jp1ac4) [inline gui/src/app/state/spend/step.rs:233]: For automated coin selection, we currently only consider confirmed coins, so I think we'll need to filter for those here to keep the same behaviour (see also https://github.com/wizardsardine/liana/issues/826).

File: gui/src/app/state/spend/step.rs [hunk 2]
```diff
@@ -175,110 +188,121 @@ impl DefineSpend {
...
+
+        let destinations: Vec<(SpendOutputAddress, Amount)> = self
+            .recipients
+            .iter()
+            .map(|recipient| {
+                (
+                    SpendOutputAddress {
+                        addr: Address::from_str(&recipient.address.value)
+                            .expect("Checked before")
+                            .assume_checked(),
```
Comment (jp1ac4) [inline gui/src/app/state/spend/step.rs:206]: I'm not sure if this matters when creating the spend, but `assume_checked` would set the network of a signet address to testnet. Following https://github.com/wizardsardine/liana/pull/813, we ignore the network when looking up addresses, but there might be some other effect of having a different network set.

File: gui/src/app/state/spend/step.rs [hunk 3]
```diff
@@ -175,110 +188,121 @@ impl DefineSpend {
...
-        let mut outputs: HashMap<Address<address::NetworkUnchecked>, u64> = HashMap::new();
-        for recipient in &self.recipients {
-            outputs.insert(
-                Address::from_str(&recipient.address.value).expect("Checked before"),
-                recipient.amount().expect("Checked before"),
-            );
+    /// redraft calculates the amount left to select and auto selects coins
+    /// if the user did not select a coin manually
+    fn redraft(&mut self, daemon: Arc<dyn Daemon + Sync + Send>) {
+        if !self.form_values_are_valid() || self.recipients.is_empty() {
```
Comment (jp1ac4) [inline gui/src/app/state/spend/step.rs:194]: Perhaps in a follow-up we could also use this function for a self-transfer to check if the user sets a feerate that is too high and will not give any change.

File: gui/src/app/view/spend/mod.rs [hunk 4]
```diff
@@ -176,7 +176,7 @@ pub fn create_spend_tx<'a>(
                                         Message::CreateSpend(CreateSpendMessage::FeerateEdited(msg))
                                     },
                                 )
-                                .warning("Invalid feerate")
+                                .warning("Feerate must be an integer inferior or equal to 1000 sats/vbyte")
```
Comment (jp1ac4) [inline gui/src/app/view/spend/mod.rs:179]: nit: I think it's more common to say "less than or equal to"

**Review by jp1ac4 — COMMENTED** [review]
I've done some testing and it's looking good. I just had a few comments, mainly about using confirmed coins only for auto coin selection.

File: gui/src/app/state/spend/step.rs (hunk 1 above)
Comment (edouardparis) [reply gui/src/app/state/spend/step.rs:233]: Ok, Thanks for the info.

File: gui/src/app/state/spend/step.rs (hunk 2 above)
Comment (edouardparis) [reply gui/src/app/state/spend/step.rs:206]: I do not think it matters, signet address are testnet address. https://github.com/wizardsardine/liana/blob/master/src/commands/mod.rs#L232 also address verification is done in the edit address message cycle and does not concern this PR.

File: gui/src/app/state/spend/step.rs (hunk 3 above)
Comment (edouardparis) [reply gui/src/app/state/spend/step.rs:194]: Yes, we could also use this function to calculate the amount a `max` button feature.

Comment (darosior) [reply gui/src/app/state/spend/step.rs:194]: Opened https://github.com/wizardsardine/liana/issues/868 to track this.

File: gui/src/app/state/spend/step.rs (hunk 2 above)
Comment (darosior) [reply gui/src/app/state/spend/step.rs:206]: > Following https://github.com/wizardsardine/liana/pull/813, we ignore the network when looking up addresses

Since this is using the spend module it's not connected to the database anymore at all.

> but there might be some other effect of having a different network set.

As long as we are only using this dummy spend for selecting coins, the address encoding should have any effect. In fact we could be taking `Script`s instead of addresses in: https://github.com/wizardsardine/liana/blob/3e0f82a71e031604fcf8bb0fd757ae95908e8ca6/src/spend.rs#L385-L389

This would avoid requiring this kind of ugliness from the callers.

**Review by jp1ac4 — APPROVED** [review]
ACK https://github.com/wizardsardine/liana/commit/a7324681e1072e4b53cd932cb49d462e9cc35956.
