### PR TITLE
gui: update `SettingState.wallet` on `WalletUpdated()` message

### LINKED ISSUE #1170: [GUI] Updated wallet settings sometimes not displayed
This happens when clicking on "Wallet" in "Settings -> Wallet" after updating a value.

To reproduce, go to Settings -> Wallet:

image

Change a fingerprint alias and click "Update":

image

Then click on "Wallet" in "Settings -> Wallet" and the previous value is shown:

image

The updated value is shown again after navigating away from this page and returning.

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR fixes #1170.

result Message from `update_key_aliases()` emited [here](https://github.com/wizardsardine/liana/blob/0a7ff2b0ea1b6f4e98946ccc1201a8d1caec8bf5/gui/src/app/state/settings/wallet.rs#L152) was not catch in `SettingState.update()`.

### CODE REVIEW

File: gui/src/app/state/settings/mod.rs [hunk 1]
```diff
@@ -84,6 +84,10 @@ impl State for SettingsState {
                     .map(|s| s.reload(daemon, wallet))
                     .unwrap_or_else(Command::none)
             }
+            Message::WalletUpdated(Ok(wallet)) => {
```
Comment (edouardparis) [inline gui/src/app/state/settings/mod.rs:87]: The message must also be passed to the self.setting update, otherwise the "Updated" green text is not shown and the button keeps the "Processing" state.

Comment (pythcoiner) [reply gui/src/app/state/settings/mod.rs:87]: done

**Review by edouardparis — APPROVED** [review]
ACK e34062a417a3533a2c42f776a495c2810775983b
